// FOOD_AND_DRINK_TYPES = CATEGORIES + EXCLUSIONS
export const FOOD_AND_DRINK_TYPES = [
    'acai_shop',
    'afghani_restaurant',
    'african_restaurant',
    'american_restaurant',
    'asian_restaurant',
    'bagel_shop',
    'bakery',
    'bar',
    'bar_and_grill',
    'barbecue_restaurant',
    'brazilian_restaurant',
    'breakfast_restaurant',
    'brunch_restaurant',
    'buffet_restaurant',
    'cafe',
    'cafeteria',
    'candy_store',
    'cat_cafe',
    'chinese_restaurant',
    'chocolate_factory',
    'chocolate_shop',
    'coffee_shop',
    'confectionery',
    'deli',
    'dessert_restaurant',
    'dessert_shop',
    'diner',
    'dog_cafe',
    'donut_shop',
    'fast_food_restaurant',
    'fine_dining_restaurant',
    'food_court',
    'french_restaurant',
    'greek_restaurant',
    'hamburger_restaurant',
    'ice_cream_shop',
    'indian_restaurant',
    'indonesian_restaurant',
    'italian_restaurant',
    'japanese_restaurant',
    'juice_shop',
    'korean_restaurant',
    'lebanese_restaurant',
    'meal_delivery',
    'meal_takeaway',
    'mediterranean_restaurant',
    'mexican_restaurant',
    'middle_eastern_restaurant',
    'pizza_restaurant',
    'pub',
    'ramen_restaurant',
    'restaurant',
    'sandwich_shop',
    'seafood_restaurant',
    'spanish_restaurant',
    'steak_house',
    'sushi_restaurant',
    'tea_house',
    'thai_restaurant',
    'turkish_restaurant',
    'vegan_restaurant',
    'vegetarian_restaurant',
    'vietnamese_restaurant',
    'wine_bar'
];

export const CATEGORIES: Record<string, string> = {
    bakery: 'Bakery',
    bar: 'Bar',
    cafe: 'Cafe',
    coffee_shop: 'Coffee Shop',
    meal_delivery: 'Delivery',
    meal_takeaway: 'Takeaway',
    pub: 'Pub',
    restaurant: 'Restaurant',
};

export const EXCLUSIONS: Record<string, string> = {
    acai_shop: 'Acai Shop',
    afghani_restaurant: 'Afghani Restaurant',
    african_restaurant: 'African Restaurant',
    american_restaurant: 'American Restaurant',
    asian_restaurant: 'Asian Restaurant',
    bagel_shop: 'Bagel Shop',
    bar_and_grill: 'Bar and Grill',
    barbecue_restaurant: 'Barbecue Restaurant',
    brazilian_restaurant: 'Brazilian Restaurant',
    breakfast_restaurant: 'Breakfast Restaurant',
    brunch_restaurant: 'Brunch Restaurant',
    buffet_restaurant: 'Buffet Restaurant',
    cafeteria: 'Cafeteria',
    candy_store: 'Candy Store',
    cat_cafe: 'Cat Cafe',
    chinese_restaurant: 'Chinese Restaurant',
    chocolate_factory: 'Chocolate Factory',
    chocolate_shop: 'Chocolate Shop',
    confectionery: 'Confectionery',
    deli: 'Deli',
    dessert_restaurant: 'Dessert Restaurant',
    dessert_shop: 'Dessert Shop',
    diner: 'Diner',
    dog_cafe: 'Dog Cafe',
    donut_shop: 'Donut Shop',
    fast_food_restaurant: 'Fast Food Restaurant',
    fine_dining_restaurant: 'Fine Dining Restaurant',
    food_court: 'Food Court',
    french_restaurant: 'French Restaurant',
    greek_restaurant: 'Greek Restaurant',
    hamburger_restaurant: 'Hamburger Restaurant',
    ice_cream_shop: 'Ice Cream Shop',
    indian_restaurant: 'Indian Restaurant',
    indonesian_restaurant: 'Indonesian Restaurant',
    italian_restaurant: 'Italian Restaurant',
    japanese_restaurant: 'Japanese Restaurant',
    juice_shop: 'Juice Shop',
    korean_restaurant: 'Korean Restaurant',
    lebanese_restaurant: 'Lebanese Restaurant',
    mediterranean_restaurant: 'Mediterranean Restaurant',
    mexican_restaurant: 'Mexican Restaurant',
    middle_eastern_restaurant: 'Middle Eastern Restaurant',
    pizza_restaurant: 'Pizza Restaurant',
    ramen_restaurant: 'Ramen Restaurant',
    sandwich_shop: 'Sandwich Shop',
    seafood_restaurant: 'Seafood Restaurant',
    spanish_restaurant: 'Spanish Restaurant',
    steak_house: 'Steak House',
    sushi_restaurant: 'Sushi Restaurant',
    tea_house: 'Tea House',
    thai_restaurant: 'Thai Restaurant',
    turkish_restaurant: 'Turkish Restaurant',
    vegan_restaurant: 'Vegan Restaurant',
    vegetarian_restaurant: 'Vegetarian Restaurant',
    vietnamese_restaurant: 'Vietnamese Restaurant',
    wine_bar: 'Wine Bar'
};

export const RADIUS_OPTIONS = [100, 200, 300, 400, 500];

export const PRICE_MAP: Record<string, string> = {
    PRICE_LEVEL_INEXPENSIVE: '$',
    PRICE_LEVEL_MODERATE: '$$',
    PRICE_LEVEL_EXPENSIVE: '$$$',
    PRICE_LEVEL_VERY_EXPENSIVE: '$$$$',
};
